name: Build and Upload Binaries

on:
  push:
    branches: [ main, test_workflow ]
  pull_request:
    branches: [ main, test_workflow ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: latest

      - name: Install Boost
        run: |
          if [ "${{ runner.os }}" == "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y libboost-all-dev
          elif [ "${{ runner.os }}" == "macOS" ]; then
            brew install boost
            brew link --overwrite boost
          fi
        shell: bash

      - name: Install Boost on Windows
        if: runner.os == 'Windows'
        run: |
          choco install boost-msvc-14.3 --no-progress
        shell: pwsh

      - name: Configure project
        run: | 
          if [ "${{ runner.os }}" == "macOS" ]; then
            cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=$(brew --prefix boost)
          else
            cmake -S . -B build -DCMAKE_BUILD_TYPE=Release 
          fi

      - name: Build project
        run: cmake --build build --config Release

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: satsuma-${{ runner.os }}-binaries
          path: |
            build/*satsuma*
